# Generated by Django 3.0.8 on 2020-08-02 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, size=None)),
                ('as_actor', models.ManyToManyField(related_name='cast', related_query_name='actor', to='api.Movie')),
                ('as_director', models.ManyToManyField(related_name='directors', related_query_name='director', to='api.Movie')),
                ('as_producer', models.ManyToManyField(related_name='producers', related_query_name='producer', to='api.Movie')),
            ],
        ),
    ]
